- hosts: Master
  roles:
  - name: "configuring Master node"
    role: Master

- hosts: Slave
  roles:
  - name: "configuring Slave node"
    role: Slave

- hosts: Master
  roles:
  - name: "Launching Wordpress and Mysql"
    role: Wordpress-MySQL
