---
# tasks file for Wordpress-MySQL
- name: "Pulling Wordpress image"
  shell: "kubectl run mywp1 --image=wordpress:5.1.1-php7.3-apache"
  register: Wordpress

- debug:
    var: "Wordpress.stdout_lines"

- name: "Pulling MySQL"
  shell: "kubectl run mydb1 --image=mysql:5.7 --env=MYSQL_ROOT_PASSWORD=redhat     --env=MYSQL_DATABASE=wpdb  --env=MYSQL_USER=hardik  --env=MYSQL_PASSWORD=redhat"
  register: MySQL

- debug:
    var: "MySQL.stdout_lines"

- name: "Exposing Wordpess"
  shell: "kubectl expose pods mywp1  --type=NodePort   --port=80"
  register: exposed
  ignore_errors: yes

- debug: 
    var: "exposed.stdout_lines"

- name: "Getting service"
  shell: "kubectl get svc"
  register: svc

- debug:
    var: "svc.stdout_lines"

- name: "Pausing playbook for pods to launch and getting IP(s)"
  pause: 
    seconds: 60

- name: "Getting database IP"
  shell: "kubectl get pods -o wide"
  register: Database_IP

- debug:
    var: "Database_IP.stdout_lines"
